import os
from pathlib import Path
from dotenv import load_dotenv

print("Current working directory:", os.getcwd())  # debug

dotenv_path = Path(__file__).parent.parent / ".env"
print("dotenv_path", dotenv_path)
load_dotenv(dotenv_path)

API_KEY = os.getenv("API_KEY")
LLM_MODEL = os.getenv("LLM_MODEL")
TEXT_EMBEDDING_MODEL = os.getenv("TEXT_EMBEDDING_MODEL")
CODE_EMBEDDING_MODEL = os.getenv("CODE_EMBEDDING_MODEL")
TEXT_RERANK_MODEL = os.getenv("TEXT_RERANK_MODEL")
CODE_RERANK_MODEL = os.getenv("CODE_RERANK_MODEL")
DATA_DIR = os.getenv("DATA_DIR")
CHUNKS_DATA_DIR = os.getenv("CHUNKS_DATA_DIR")
VECTORSTORE_DATA_DIR = os.getenv("VECTORSTORE_DATA_DIR")
VECTORSTORE_DATA_ABLATION_DIR = os.getenv("VECTORSTORE_DATA_ABLATION_DIR")
MAX_CHUNK_CHARS = os.getenv("MAX_CHUNK_CHARS")
ANTIPATTERN_TYPE = os.getenv("ANTIPATTERN_TYPE")
CH_CHUNK_TYPE_WEIGHT_PATH = os.getenv("CH_CHUNK_TYPE_WEIGHT_PATH")
MH_CHUNK_TYPE_WEIGHT_PATH = os.getenv("MH_CHUNK_TYPE_WEIGHT_PATH")
AWD_CHUNK_TYPE_WEIGHT_PATH = os.getenv("AWD_CHUNK_TYPE_WEIGHT_PATH")
CH_CHUNK_TYPE_ABLATION_WEIGHT_PATH = os.getenv("CH_CHUNK_TYPE_ABLATION_WEIGHT_PATH")
MH_CHUNK_TYPE_ABLATION_WEIGHT_PATH = os.getenv("MH_CHUNK_TYPE_ABLATION_WEIGHT_PATH")
AWD_CHUNK_TYPE_ABLATION_WEIGHT_PATH = os.getenv("AWD_CHUNK_TYPE_ABLATION_WEIGHT_PATH")


print(f"DATA_DIR loaded: {DATA_DIR}")
